# Generated by Django 5.1.4 on 2026-05-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chalets", "0001_initial"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم العميل")),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="رقم التليفون"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "عميل",
                "verbose_name_plural": "العملاء",
                "db_table": "customers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "guests_count",
                    models.PositiveIntegerField(default=1, verbose_name="عدد الأفراد"),
                ),
                (
                    "check_in",
                    models.DateField(db_index=True, verbose_name="تاريخ الدخول"),
                ),
                (
                    "check_out",
                    models.DateField(db_index=True, verbose_name="تاريخ الخروج"),
                ),
                (
                    "days_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الأيام"),
                ),
                (
                    "nightly_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر الليلة"
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=12, verbose_name="الخصم"
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "final_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المبلغ النهائي",
                    ),
                ),
                (
                    "deposit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="عربون"
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="المتبقي",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "مدفوع"),
                            ("unpaid", "غير مدفوع"),
                            ("partial", "دفعة جزئية"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "قيد الانتظار"),
                            ("confirmed", "مؤكد"),
                            ("checked_in", "تم الدخول"),
                            ("checked_out", "تم الخروج"),
                            ("cancelled", "ملغي"),
                        ],
                        db_index=True,
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                (
                    "profit",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=14, verbose_name="الربح"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="chalets.chalet",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="bookings.customer",
                    ),
                ),
            ],
            options={
                "verbose_name": "حجز",
                "verbose_name_plural": "الحجوزات",
                "db_table": "bookings",
                "ordering": ["-check_in"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("payment_date", models.DateField()),
                ("payment_method", models.CharField(default="cash", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="bookings.booking",
                    ),
                ),
                (
                    "owner_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="owners.ownerrentalcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "دفعة",
                "verbose_name_plural": "الدفعات",
                "db_table": "payments",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in", "check_out"], name="bookings_check_i_759ffa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["chalet", "check_in", "check_out"],
                name="bookings_chalet__df8397_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["payment_status", "status"], name="bookings_payment_5bedf5_idx"
            ),
        ),
    ]
