# Generated by Django 5.1.4 on 2026-05-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0001_initial"),
        ("chalets", "0001_initial"),
        ("owners", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("owner_contract_expiry", "انتهاء عقد المالك"),
                            ("payment_remaining", "دفعة متبقية"),
                            ("upcoming_booking", "حجز قادم"),
                            ("checkout_reminder", "انتهاء إقامة"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "منخفض"),
                            ("medium", "متوسط"),
                            ("high", "عالي"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "related_booking",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="bookings.booking",
                    ),
                ),
                (
                    "related_chalet",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chalets.chalet",
                    ),
                ),
                (
                    "related_contract",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="owners.ownerrentalcontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "إشعار",
                "verbose_name_plural": "الإشعارات",
                "db_table": "notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_read", "created_at"],
                        name="notificatio_is_read_9b69ad_idx",
                    )
                ],
            },
        ),
    ]
