# Generated by Django 5.1.4 on 2026-05-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chalets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("maintenance", "صيانة"),
                            ("electricity", "كهرباء"),
                            ("water", "مياه"),
                            ("cleaning", "تنظيف"),
                            ("internet", "إنترنت"),
                            ("salaries", "مرتبات"),
                            ("other", "أخرى"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date", models.DateField(db_index=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="chalets.chalet",
                    ),
                ),
            ],
            options={
                "verbose_name": "مصروف",
                "verbose_name_plural": "المصروفات",
                "db_table": "expenses",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["chalet", "date"], name="expenses_chalet__dee20c_idx"
                    ),
                    models.Index(
                        fields=["expense_type", "date"],
                        name="expenses_expense_0190ac_idx",
                    ),
                ],
            },
        ),
    ]
