# Generated by Django 5.1.4 on 2026-05-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chalet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم الشاليه")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="كود الشاليه",
                    ),
                ),
                ("location", models.CharField(max_length=300, verbose_name="الموقع")),
                (
                    "city",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="الوصف")),
                (
                    "rooms_count",
                    models.PositiveIntegerField(default=1, verbose_name="عدد الغرف"),
                ),
                (
                    "bathrooms_count",
                    models.PositiveIntegerField(default=1, verbose_name="عدد الحمامات"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=4, verbose_name="عدد الأفراد"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "متاح"),
                            ("rented", "مؤجر"),
                            ("maintenance", "صيانة"),
                        ],
                        db_index=True,
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "features",
                    models.JSONField(blank=True, default=list, verbose_name="المميزات"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="ملاحظات")),
                (
                    "nightly_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="سعر الليلة",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "شاليه",
                "verbose_name_plural": "الشاليهات",
                "db_table": "chalets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "city"], name="chalets_status_30e566_idx"
                    ),
                    models.Index(fields=["code"], name="chalets_code_690867_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChaletImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="chalets/%Y/%m/", verbose_name="الصورة"
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="chalets.chalet",
                    ),
                ),
            ],
            options={
                "verbose_name": "صورة شاليه",
                "verbose_name_plural": "صور الشاليهات",
                "db_table": "chalet_images",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
    ]
