# Generated by Django 5.1.4 on 2026-05-20 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chalets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="اسم المالك")),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="رقم التليفون"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "مالك",
                "verbose_name_plural": "الملاك",
                "db_table": "owners",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OwnerRentalContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="سعر اليوم"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="تاريخ البداية"),
                ),
                (
                    "end_date",
                    models.DateField(db_index=True, verbose_name="تاريخ النهاية"),
                ),
                (
                    "days_count",
                    models.PositiveIntegerField(default=0, verbose_name="عدد الأيام"),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="إجمالي التكلفة",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "نقدي"),
                            ("transfer", "تحويل بنكي"),
                            ("check", "شيك"),
                        ],
                        default="cash",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "مدفوع"),
                            ("unpaid", "غير مدفوع"),
                            ("partial", "دفعة جزئية"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chalet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_contracts",
                        to="chalets.chalet",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contracts",
                        to="owners.owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "عقد إيجار من المالك",
                "verbose_name_plural": "عقود الإيجار من الملاك",
                "db_table": "owner_rental_contracts",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["start_date", "end_date"],
                        name="owner_renta_start_d_e5a44a_idx",
                    ),
                    models.Index(
                        fields=["payment_status"], name="owner_renta_payment_edcbcb_idx"
                    ),
                ],
            },
        ),
    ]
